workflows:
  flutter-workflow:
    name: Flutter Build
    instance_type: mac_mini_m2
    environment:
      flutter: 3.29.0
    scripts:
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
